name: flutter_translations_updater
description: CLI tool for automatic updating translations in flutter projects.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: 2.3.1


dev_dependencies:
  lints: 2.0.0
